---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  # username: admin
  # password: 12345
  # Data has to base64 encoded. I encoded it ike this (on Linux):
  # echo -n 'admin' | base64
  # echo -n '12345' | base64
  username: YWRtaW4=
  password: MTIzNDU=
# OR if you don't want to base64 encode you can use the field stringData instead of data
#stringData:
#  username: 'admin'
#  password: '12345'

---
apiVersion: v1
kind: Pod
metadata:
  name: consumesec-env
spec:
  volumes: # load secret as volume (it is mounted in the container below)
  - name: secretvol
    secret:
      secretName: mysecret
  containers:
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    env: # load a single key from a secret
      - name: MY_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
    envFrom: # load the whole secret
      - secretRef:
          name: mysecret
    volumeMounts:
      - name: secretvol
        mountPath: "/tmp/apikey"
        readOnly: true

