apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgchart
  labels:
    app: orgchart
spec:
  selector:
    matchLabels:
      app: orgchart
  replicas: 1
  template:  
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'webapp'
        vault.hashicorp.com/agent-inject-secret-webapp-config.txt: 'secret/data/webapp/config'
      labels:
        app: orgchart
    spec:
      serviceAccountName: sa-vault
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1